'use strict';
(async()=>{
 const msg=document.getElementById('message');if(!dc4HasSession('admin')){location.replace('V2/admin.html');return;}
 try{const cfg=await(await dc4Fetch('config.json',{cache:'no-store'})).json();
 const root='https://filiperod-byte.github.io/DomingosdaCunha4/';
 const grid=document.getElementById('labels');for(const f of cfg.building.floors){const card=document.createElement('article');card.className='qr-label selected';const label=document.createElement('label');label.className='check no-print';const check=document.createElement('input');check.type='checkbox';check.checked=true;check.setAttribute('aria-label','Imprimir piso '+f.floor);check.onchange=()=>card.classList.toggle('selected',check.checked);label.append(check,'Incluir na impressão');const logo=document.createElement('img');logo.className='logo';logo.src='assets/logo-qrcode.png';logo.alt='Domingos da Cunha nº 4';const title=document.createElement('h2');title.textContent='Piso '+f.floor;const text=document.createElement('p');text.textContent='Comunicar um problema neste piso';const qr=document.createElement('img');qr.className='qr';qr.src='assets/qr-floors/piso-'+f.floor+'.svg';qr.alt='QR para comunicar problema no piso '+f.floor;const hint=document.createElement('p');hint.textContent='Leia o QR, escolha o tipo de problema e descreva a situação.';const small=document.createElement('small');small.textContent='Login de morador apenas ao enviar. Para um extintor, utilize o QR dedicado.';const link=document.createElement('a');link.href=root+'general-report.html?floor='+f.floor;link.textContent=link.href;card.append(label,logo,title,text,qr,hint,small,document.createElement('br'),link);grid.append(card);}
 const select=value=>grid.querySelectorAll('input').forEach(c=>{c.checked=value;c.onchange()});document.getElementById('all').onclick=()=>select(true);document.getElementById('none').onclick=()=>select(false);
 document.getElementById('print').onclick=async()=>{const cards=[...grid.querySelectorAll('.selected')];if(!cards.length){msg.textContent='Selecione pelo menos um piso.';return;}try{await Promise.all(cards.flatMap(c=>[...c.querySelectorAll('img')]).map(i=>i.decode()));msg.textContent='Etiquetas prontas para impressão.';window.print();}catch(e){msg.textContent='Uma imagem não carregou. Atualize a página antes de imprimir.';}};
 msg.textContent='Selecione os pisos e imprima em A4. Pode guardar como PDF no diálogo de impressão.';
 }catch(e){msg.textContent='Não foi possível preparar as etiquetas. Atualize a página.';}
})();
