/* Reutiliza autenticação, fotografia e transporte do reporte dedicado ao extintor. */
let GENERAL_ITEMS=[],GENERAL_REQUEST=null,GENERAL_CONFIRM=new URLSearchParams(location.search).get('confirm')||'',GENERAL_READY=false;
const GC=window.DC4_OCCURRENCE_CATALOG;
findPointFromUrl=function(){const p=new URLSearchParams(location.search);if(p.get('scope')==='general')return {scope:'general',floor:null,label:'Prédio / Zonas gerais'};if(!p.has('floor')||!p.get('floor').trim()||!GC.floors.includes(Number(p.get('floor'))))throw new Error('Piso inválido.');return{scope:'floor',floor:Number(p.get('floor')),label:'Piso '+Number(p.get('floor'))};};
fillReasons=function(){
 const cats=GC.categories.filter(c=>c.scope==='both'||c.scope===POINT.scope);
 $('category').replaceChildren(new Option('Escolher tipo de problema',''),...cats.map(c=>new Option(c.label,c.id)));
 const requested=new URLSearchParams(location.search).get('category');if(cats.some(c=>c.id===requested))$('category').value=requested;
 const update=()=>{const cat=cats.find(c=>c.id===$('category').value);$('reason').replaceChildren(new Option('Selecionar motivo',''),...(cat?.reasons||[]).map(r=>new Option(r,r)));renderGeneralExisting();};
 $('category').onchange=update;update();$('locationDetail').required=POINT.scope==='general';
};
renderPoint=function(){document.title='Comunicar problema · '+POINT.label;$('introText').textContent='Escolha o tipo de problema. O login só é necessário ao enviar.';$('pointCard').innerHTML='<p class="point-title">'+escapeHtml(POINT.label)+'</p><span class="status pending" id="statusBadge">A consultar ocorrências…</span><div class="existing" id="existingBox"></div><button class="btn btn-secondary" id="refreshGeneral" type="button">Atualizar ocorrências</button>';$('refreshGeneral').onclick=loadExisting;};
loadExisting=async function(){try{const r=await apiGet('general.status');if(!r.success||!Array.isArray(r.occurrences))throw new Error('Serviço indisponível');GENERAL_ITEMS=r.occurrences;GENERAL_READY=true;renderGeneralExisting();}catch(e){GENERAL_READY=false;$('statusBadge').textContent='Estado por confirmar';$('existingBox').textContent='Não foi possível consultar as ocorrências. Pode preencher e tentar atualizar novamente.';}};
function renderGeneralExisting(){if(!$('existingBox')||!GENERAL_READY)return;const matches=GENERAL_ITEMS.filter(o=>o.scope===POINT.scope&&(POINT.scope==='general'||Number(o.floor)===POINT.floor)&&(! $('category').value||o.category===$('category').value)&&o.status!=='RESOLVIDO');$('statusBadge').textContent=matches.length?matches.length+' ocorrência(s) aberta(s)':'Sem ocorrência validada neste tipo';$('existingBox').replaceChildren();for(const o of matches){const box=document.createElement('div');box.className='card';const title=document.createElement('strong');title.textContent=o.reason+' · '+GC.statuses[o.status];const desc=document.createElement('p');desc.textContent=o.description;desc.style.whiteSpace='pre-wrap';const details=document.createElement('p');details.textContent=[o.location,new Date(o.reportedAt).toLocaleDateString('pt-PT'),o.scheduledFor?'Intervenção: '+o.scheduledFor:''].filter(Boolean).join(' · ');const btn=document.createElement('button');btn.type='button';btn.className='btn btn-secondary';btn.textContent='Também verifiquei esta situação';btn.onclick=()=>{GENERAL_CONFIRM=o.id;if(!dc4HasSession('resident'))openAuth();else sendReport();};box.append(title,desc,details,btn);$('existingBox').append(box);}if(!matches.length)$('existingBox').textContent='Os reportes pendentes ainda não aparecem nesta consulta pública.';
 if(GENERAL_CONFIRM){const item=matches.find(o=>o.id===GENERAL_CONFIRM);if(item){const btn=document.createElement('button');btn.type='button';btn.className='btn btn-primary';btn.textContent='Confirmar que também verifiquei';btn.onclick=()=>{if(!dc4HasSession('resident'))openAuth();else sendReport()};$('existingBox').prepend(btn);}}
}
submit=async function(ev){ev.preventDefault();if(BUSY)return;if(!GENERAL_REQUEST){GENERAL_CONFIRM='';if(!$('category').value||!$('reason').value||!$('notes').value.trim()){setMsg('err','Preencha tipo, motivo e descrição.');return;}}if(!dc4HasSession('resident')){openAuth();return;}await sendReport();};
function freezeGeneral(frozen){['category','reason','notes','locationDetail','cameraBtn','fileBtn','cameraInput','fileInput'].forEach(id=>$(id).disabled=frozen);$('existingBox').querySelectorAll('button').forEach(b=>b.disabled=frozen);}
sendReport=async function(){if(BUSY)return;BUSY=true;$('submitBtn').disabled=true;freezeGeneral(true);try{
 if(!GENERAL_REQUEST){const id=crypto.randomUUID();if(GENERAL_CONFIRM)GENERAL_REQUEST={action:'general.confirm',data:{requestId:id,occurrenceId:GENERAL_CONFIRM}};else{const photo=FILE?await fileToPayload(FILE):null;GENERAL_REQUEST={action:'general.report',data:{requestId:id,scope:POINT.scope,floor:POINT.floor,category:$('category').value,reason:$('reason').value,description:$('notes').value.trim(),location:$('locationDetail').value.trim(),photoBase64:photo?.base64||'',photoType:photo?.type||''}};}}
 const r=await apiPost(GENERAL_REQUEST.action,GENERAL_REQUEST.data);
 if(!r.success){if(r.code==='VALIDATION_ERROR')GENERAL_REQUEST=null;throw new Error(r.message||'Não foi possível guardar.');}
 const confirmed=GENERAL_REQUEST.action==='general.confirm';GENERAL_REQUEST=null;GENERAL_CONFIRM='';
 if(!confirmed){$('reportForm').reset();FILE=null;$('photoMeta').textContent='Sem fotografia selecionada.';fillReasons();}
 setMsg('ok',confirmed?'Confirmação registada. Não foi criada outra ocorrência.':'Reporte recebido. Aguarda validação da administração.');await loadExisting();
 }catch(e){if(e.code==='AUTH_REQUIRED'){openAuth();$('authMsg').textContent='A sessão terminou. Entre para concluir sem perder os dados.';}else setMsg('err',e.message+(GENERAL_REQUEST?' O envio não foi confirmado. Use «Repetir envio»; será reutilizado o mesmo pedido para evitar duplicados.':''));}
 finally{BUSY=false;$('submitBtn').disabled=false;$('submitBtn').textContent=GENERAL_REQUEST?'Repetir envio':'Submeter reporte';freezeGeneral(!!GENERAL_REQUEST);}}
