'use strict';
const AC=window.DC4_OCCURRENCE_CATALOG;
let cfg,records=[],pendingSave=null;
const el=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function call(action,data={}){const r=await dc4Fetch(cfg.backendUrl,{method:'POST',body:JSON.stringify({action,...data})});const x=await r.json();if(!x.success){const e=new Error(x.message||'Não foi possível concluir.');e.confirmed=x.code==='VALIDATION_ERROR';throw e;}return x;}
function render(){el('items').innerHTML=records.filter(o=>!el('filter').value||o.status===el('filter').value).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(o=>`<form class="card" data-id="${esc(o.id)}"><span class="tag">${esc(AC.statuses[o.status])}</span><h2>${esc(o.scope==='general'?'Prédio / Zonas gerais':'Piso '+o.floor)} · ${esc(AC.categories.find(c=>c.id===o.category)?.label)}</h2><p><strong>${esc(o.reason)}</strong></p><details><summary>Reporte original e histórico</summary><p>Autor: ${esc(o.reportedBy)} · ${esc(o.reportedAt)}</p><p>${esc(o.location)}</p><p class="pre">${esc(o.description)}</p>${/^https:\/\/drive.google.com\//.test(o.photoUrl||'')?`<a href="${esc(o.photoUrl)}" target="_blank" rel="noopener">Abrir fotografia (acesso Drive autorizado)</a>`:''}<ul class="history">${(o.history||[]).map(h=>`<li>${esc(h.at)} · ${esc(AC.statuses[h.status])}</li>`).join('')}</ul></details><p>${(o.confirmations||[]).length} morador(es) confirmou(aram) esta situação.</p><label>Estado<select name="status">${Object.entries(AC.statuses).map(([k,v])=>`<option value="${k}" ${k===o.status?'selected':''}>${v}</option>`).join('')}</select></label><label>Localização pública<input name="publicLocation" maxlength="160" value="${esc(o.publicLocation)}"></label><label>Descrição para os moradores<textarea name="publicDescription" maxlength="2000">${esc(o.publicDescription)}</textarea></label><button type="button" data-copy="${esc(o.id)}">Usar texto original para revisão</button><p class="muted">Reveja os dados pessoais antes de publicar. Recebido e Não validado não são públicos.</p><label>Data da intervenção<input type="date" name="scheduledFor" value="${esc(o.scheduledFor||'')}"></label><label>Resolução para os moradores<textarea name="publicResolution" maxlength="2000">${esc(o.publicResolution||'')}</textarea></label><label>Notas internas da administração<textarea name="internalNotes" maxlength="4000">${esc(o.internalNotes||'')}</textarea></label><p class="save-message" role="status"></p><button class="primary" type="submit">Guardar atualização</button></form>`).join('')||'<p>Sem ocorrências neste estado.</p>';
 el('items').querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{const o=records.find(o=>o.id===b.dataset.copy),f=b.closest('form');f.elements.publicDescription.value=o.description;f.elements.publicLocation.value=o.location;});el('items').querySelectorAll('form').forEach(f=>f.onsubmit=ev=>save(ev,f));}
async function refresh(){el('refresh').disabled=true;el('message').textContent='A carregar…';try{records=(await call('general.admin',{_method:'GET'})).occurrences;render();el('message').textContent='Lista atualizada.';}catch(e){el('message').textContent=e.message;}finally{el('refresh').disabled=false;}}
async function save(ev,f){ev.preventDefault();if(pendingSave&&pendingSave.id!==f.dataset.id)return;const button=f.querySelector('[type=submit]');if(button.disabled)return;const o=records.find(o=>o.id===f.dataset.id);if(!pendingSave)pendingSave={id:o.id,payload:{...Object.fromEntries(new FormData(f)),occurrenceId:o.id,revision:o.revision,requestId:crypto.randomUUID()}};button.disabled=true;el('refresh').disabled=true;el('filter').disabled=true;f.querySelectorAll('input,textarea,select,button').forEach(e=>e.disabled=true);try{await call('general.update',pendingSave.payload);pendingSave=null;await refresh();}catch(e){if(e.confirmed){pendingSave=null;f.querySelectorAll('input,textarea,select,button').forEach(e=>e.disabled=false);}f.querySelector('.save-message').textContent=e.message+(e.confirmed?' Corrija o formulário ou atualize a lista.':' Pode repetir o mesmo envio.');if(e.code==='AUTH_REQUIRED'){location.assign('V2/admin.html');return;}button.disabled=false;button.textContent='Repetir envio';}finally{if(!pendingSave){el('refresh').disabled=false;el('filter').disabled=false;}}}
(async()=>{if(!dc4HasSession('admin')){location.replace('V2/admin.html');return;}Object.entries(AC.statuses).forEach(([k,v])=>el('filter').add(new Option(v,k)));el('filter').onchange=render;el('refresh').onclick=refresh;try{cfg=await(await dc4Fetch('config.json',{cache:'no-store'})).json();await refresh();}catch(e){el('message').textContent=e.message;}})();
