'use strict';
const OC=window.DC4_OCCURRENCE_CATALOG;
const labelFloor=f=>Number(f)===0?'Piso 0':Number(f)<0?'Garagem · piso '+f:'Piso '+f;
const ehtml=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
let config,items=[],ext=[],loaded=false;
const params=new URLSearchParams(location.search),general=params.get('scope')==='general',hasFloor=params.has('floor');
const floor=hasFloor?Number(params.get('floor')):null,selected=general||hasFloor;
const floorUrl=f=>'occurrences.html?floor='+f;
function matches(o){return general?o.scope==='general':o.scope==='floor'&&Number(o.floor)===floor;}
function issueMarkup(o){return '<article class="card"><span class="tag">'+ehtml(OC.statuses[o.status])+'</span><h3>'+ehtml(OC.categories.find(c=>c.id===o.category)?.label||o.category)+' · '+ehtml(o.reason)+'</h3><p class="pre">'+ehtml(o.description)+'</p><p>'+ehtml(o.location||'')+'</p><small>Registado em '+ehtml(new Date(o.reportedAt).toLocaleDateString('pt-PT'))+'</small>'+(o.scheduledFor?'<p>Intervenção: '+ehtml(o.scheduledFor)+'</p>':'')+(o.resolution?'<p class="pre">Resolução: '+ehtml(o.resolution)+'</p>':'')+(o.status!=='RESOLVIDO'?'<p><a class="btn" href="general-report.html?'+(general?'scope=general':'floor='+floor)+'&category='+encodeURIComponent(o.category)+'&confirm='+encodeURIComponent(o.id)+'">Também verifiquei esta situação</a></p>':'')+'</article>';}
function render(){
 document.getElementById('buildingView').hidden=selected;document.getElementById('floorView').hidden=!selected;
 if(selected){
  document.getElementById('floorTitle').textContent=general?'Prédio / Zonas gerais':labelFloor(floor);
  const cats=OC.categories.filter(c=>c.scope==='both'||c.scope===(general?'general':'floor'));
  let links=cats.map(c=>'<a class="choice" href="general-report.html?'+(general?'scope=general':'floor='+floor)+'&category='+c.id+'"><strong>'+ehtml(c.label)+'</strong><span>›</span></a>').join('');
  if(!general){const f=config.building.floors.find(f=>Number(f.floor)===floor);links='<div class="card"><h3>🧯 Extintores / Segurança contra incêndio</h3><div class="toolbar">'+(f.extinguishers||[]).map(p=>'<a class="btn" href="qrcode-report.html?floor='+floor+'&point='+encodeURIComponent(p.point)+'&from=occurrences">'+ehtml(p.label)+(loaded&&ext.some(x=>Number(x.floor)===floor&&x.point===p.point)?' · Ocorrência aberta':'')+'</a>').join('')+'</div></div>'+links;}
  document.getElementById('categories').innerHTML=links;
  document.getElementById('openItems').innerHTML=loaded?(items.filter(o=>matches(o)&&o.status!=='RESOLVIDO').map(issueMarkup).join('')||'<p>Sem ocorrências gerais validadas em aberto.</p>'):'<p>Estado por confirmar. Pode preparar um reporte.</p>';
  document.getElementById('resolvedItems').innerHTML=loaded?(items.filter(o=>matches(o)&&o.status==='RESOLVIDO').map(issueMarkup).join('')||'<p>Sem ocorrências resolvidas.</p>'):'<p>Estado por confirmar.</p>';
 }else document.getElementById('facade').innerHTML=config.building.floors.map(f=>{const count=items.filter(o=>o.scope==='floor'&&Number(o.floor)===Number(f.floor)&&o.status!=='RESOLVIDO').length+ext.filter(o=>Number(o.floor)===Number(f.floor)).length;return '<a class="floor-row btn" href="'+floorUrl(f.floor)+'"><span class="floor-num">'+f.floor+'</span>'+ (f.type==='garage'?'<span class="garage-windows">GARAGEM</span>':f.type==='service'?'<span class="service-windows" aria-hidden="true"><i></i><i></i><i></i><i></i></span>':'<span class="windows" aria-hidden="true">'+'<i></i>'.repeat(f.fractions||3)+'</span>')+'<span class="floor-count">'+(loaded?(count?count+' aberta'+(count>1?'s':''):'Sem ocorrências validadas'):'Por confirmar')+' ›</span></a>';}).join('');
}
async function refresh(){document.getElementById('refresh').disabled=true;document.getElementById('loadState').textContent='A consultar ocorrências…';loaded=false;render();try{const get=async(action,extra={})=>{const u=new URL(config.backendUrl);u.searchParams.set('action',action);Object.entries(extra).forEach(([k,v])=>u.searchParams.set(k,v));return(await dc4Fetch(u,{cache:'no-store'})).json()};const [g,x]=await Promise.all([get('general.status'),get('status',{details:'public'})]);if(!g.success||!Array.isArray(g.occurrences)||!x.success)throw new Error('Consulta indisponível.');items=g.occurrences;ext=x.reported||[];loaded=true;document.getElementById('loadState').textContent='Atualizado às '+new Date().toLocaleTimeString('pt-PT');}catch(e){document.getElementById('loadState').textContent='Estado por confirmar. Não foi possível atualizar. Tente novamente.';}finally{render();document.getElementById('refresh').disabled=false;}}
(async()=>{try{config=await(await dc4Fetch('config.json',{cache:'no-store'})).json();if(hasFloor&&(!params.get('floor').trim()||!OC.floors.includes(floor)))throw new Error('Piso inválido.');render();document.getElementById('refresh').onclick=refresh;await refresh();}catch(e){document.getElementById('loadState').textContent=e.message;document.getElementById('buildingView').hidden=true;document.getElementById('floorView').hidden=true;}})();
