const test=require('node:test'),assert=require('node:assert/strict');
const {harness,bundled}=require('./harness.cjs');
function setup(){const b=harness(bundled());b.initialize();b.context.setupGeneralOccurrences();const c=b.sheets.get('CONFIG');c.rows.find(r=>r[0]==='ADMIN_PIN')[1]='98765432';const a=b.post('garage.loginAdmin',{email:'admin@example.invalid',pin:'98765432'}).token;const s=b.sheets.get('CONDOMINOS');const row={ID:'resident-1',Nome:'Pessoa teste',Piso:'9',Fracao:'B',Estado:'APROVADO',PIN:'654321',PINAtivo:true};s.rows.push(s.rows[0].map(h=>row[h]??''));const r=b.post('garage.loginPin',{pin:'654321'}).token;return {b,a,r};}
const payload={requestId:'request-1234567890',scope:'floor',floor:-2,category:'iluminacao',reason:'Luz apagada',description:'Luz junto à escada apagada',location:'Escada'};
function adminList(b,a){return b.post('general.admin',{token:a,_method:'GET'}).occurrences;}
function publish(b,a,id,extra={}){const o=adminList(b,a).find(o=>o.id===id);return b.post('general.update',{token:a,requestId:'update-'+String(o.revision).padStart(12,'0'),occurrenceId:id,revision:o.revision,status:'EM_ANALISE',publicDescription:'Luz apagada na escada',publicLocation:'Escada',internalNotes:'Fornecedor e contacto privados',...extra});}
test('novas rotas exigem sessão e perfil administrativo',()=>{const {b,r}=setup();assert.equal(b.post('general.report',payload).code,'AUTH_REQUIRED');assert.equal(b.post('general.confirm',{occurrenceId:'x'}).code,'AUTH_REQUIRED');assert.equal(b.get('general.admin').code,'AUTH_REQUIRED');assert.equal(b.post('general.admin',{token:r,_method:'GET'}).code,'FORBIDDEN');assert.equal(b.post('general.update',{token:r}).code,'FORBIDDEN');});
test('reporte pendente privado, publicação explícita e resolução',()=>{const {b,a,r}=setup();const x=b.post('general.report',{...payload,token:r,_actor:'admin',_actorName:'Falso'});assert.ok(x.success);assert.equal(b.get('general.status').occurrences.length,0);const raw=adminList(b,a)[0];assert.equal(raw.reportedBy,'Pessoa teste');assert.equal(raw.status,'RECEBIDO');assert.equal(publish(b,a,x.occurrenceId).success,true);const pub=b.get('general.status').occurrences[0];assert.equal(pub.description,'Luz apagada na escada');for(const k of ['reportedBy','reporterId','photoUrl','internalNotes','history'])assert.equal(k in pub,false,k);assert.equal(JSON.stringify(pub).includes('Fornecedor'),false);assert.equal(publish(b,a,x.occurrenceId,{status:'AGENDADO',scheduledFor:'2026-10-10'}).success,true);assert.equal(publish(b,a,x.occurrenceId,{status:'RESOLVIDO',publicResolution:'Lâmpada substituída'}).success,true);assert.equal(b.get('general.status').occurrences[0].resolution,'Lâmpada substituída');});
test('resposta perdida depois de guardar não duplica o reporte ou a fotografia',()=>{const {b,r}=setup();const sh=b.sheets.get('OCORRENCIAS_GERAIS'),append=sh.appendRow.bind(sh);let fail=true;sh.appendRow=row=>{append(row);if(fail){fail=false;throw new Error('Resposta perdida');}return sh;};const p={...payload,token:r,photoBase64:'YQ==',photoType:'image/jpeg'};assert.equal(b.post('general.report',p).success,false);const retry=b.post('general.report',p);assert.equal(retry.success,true);assert.equal(retry.replayed,true);assert.equal(sh.rows.length,2);assert.equal(b.counts.files,1);assert.equal(b.counts.shares,0);assert.equal(b.post('general.report',{...p,description:'Alterado'}).success,false);});
test('confirmação não cria outra ocorrência e conta cada morador apenas uma vez',()=>{const {b,a,r}=setup();const x=b.post('general.report',{...payload,token:r});publish(b,a,x.occurrenceId);for(let i=0;i<2;i++)assert.equal(b.post('general.confirm',{token:r,occurrenceId:x.occurrenceId,requestId:'confirm-123456789'+i}).success,true);assert.equal(b.get('general.status').occurrences.length,1);assert.equal(b.get('general.status').occurrences[0].confirmations,1);});
test('piso 0, âmbito geral, validações e conflito de edição',()=>{const {b,a,r}=setup();for(const patch of [{floor:1},{floor:''},{category:'elevadores'},{reason:'Inventado'},{description:''},{requestId:'curto'}])assert.equal(b.post('general.report',{...payload,...patch,token:r}).success,false);assert.equal(b.post('general.report',{...payload,token:r,floor:0}).success,true);const x=b.post('general.report',{...payload,token:r,requestId:'request-general-123',scope:'general',floor:null,category:'elevadores',reason:'Fora de serviço',location:'Elevador do lado esquerdo'});assert.equal(x.success,true);assert.equal(publish(b,a,x.occurrenceId,{revision:0}).success,false);assert.equal(publish(b,a,x.occurrenceId,{status:'AGENDADO',scheduledFor:''}).success,false);assert.equal(publish(b,a,x.occurrenceId,{status:'RESOLVIDO',publicResolution:''}).success,false);});
test('preparação repetida preserva a folha nova e as folhas antigas',()=>{const {b,r}=setup();b.post('general.report',{...payload,token:r});const before=b.snapshot();b.context.setupGeneralOccurrences();assert.deepEqual(b.snapshot(),before);});
