// Configuração e esquema atuais. Não colocar credenciais neste ficheiro.
const CONFIG = {
  APP_NAME: 'Domingos da Cunha 4',
  TZ: 'Europe/Lisbon',
  SPREADSHEET_ID: '16vz1ZIKkCI7NfAf2ZSVCNLEafBn4Svtu7UaRe0WdpBU',
  ROOT_FOLDER_ID: '1Ppu0Tk5zLrOWBQGwJtH_GE2kpSanWyb9',
  ADMIN_EMAIL: 'filiperod@gmail.com',
  PIN_MIN_LENGTH: 4,
  SHEETS: {
    REGISTOS: 'REGISTOS',
    ESTADO: 'ESTADO_EXTINTORES',
    FECHOS: 'HISTORICO_FECHOS'
  },
  SUBFOLDERS: {
    REPORTS: 'REPORTES_EXTINTORES',
    CLOSES: 'FECHOS_EXTINTORES'
  },
  PROPS: {
    PIN_HASH: 'BACKOFFICE_PIN_HASH',
    PIN_SALT: 'BACKOFFICE_PIN_SALT',
    PIN_UPDATED_AT: 'BACKOFFICE_PIN_UPDATED_AT'
  }
};

const REQUIRED_HEADERS = {
  REGISTOS: [
    'TIMESTAMP','EVENTO','OCCURRENCE_ID','FLOOR','FLOOR_LABEL','POINT','LOCATION','REPORTED_BY','REASON','NOTES','PHOTO_FILE_ID','PHOTO_FILE_URL','PHOTO_FILE_NAME','STATUS_BEFORE','STATUS_AFTER','SOURCE','CLIENT_TS','EXTRA_JSON'
  ],
  ESTADO: [
    'LAST_UPDATED','STATUS','OCCURRENCE_ID','FLOOR','FLOOR_LABEL','POINT','LOCATION','REPORTED_AT','REPORTED_BY','REASON','NOTES','PHOTO_FILE_ID','PHOTO_FILE_URL','PHOTO_FILE_NAME','CLOSED_AT','CLOSE_NOTES','CLOSE_PHOTO_FILE_ID','CLOSE_PHOTO_FILE_URL','CLOSE_PHOTO_FILE_NAME','LAST_EVENT'
  ],
  FECHOS: [
    'TIMESTAMP','OCCURRENCE_ID','FLOOR','FLOOR_LABEL','POINT','LOCATION','REPORTED_AT','REPORTED_BY','REASON','OPEN_NOTES','CLOSE_NOTES','CLOSE_PHOTO_FILE_ID','CLOSE_PHOTO_FILE_URL','CLOSE_PHOTO_FILE_NAME','SOURCE','CLIENT_TS'
  ]
};

const OPEN_STATUSES = ['ABERTA', 'OPEN', 'ALERTA', 'REPORTADO'];
const PENDING_STATUSES = ['PENDENTE_VALIDACAO', 'PENDENTE', 'PENDING_VALIDATION'];

const GARAGE_RESIDENTIAL_STRUCTURE = {
  '10': ['A', 'B'],
  '9': ['A', 'B', 'C'],
  '8': ['A', 'B', 'C'],
  '7': ['A', 'B', 'C'],
  '6': ['A', 'B', 'C'],
  '5': ['A', 'B', 'C'],
  '4': ['A', 'B', 'C'],
  '3': ['A', 'B', 'C'],
  '2': ['A', 'B', 'C'],
  '-1': ['GARAGEM'],
  '-2': ['GARAGEM'],
  '-3': ['LUGAR_GARAGEM']
};
